# Generated by Django 5.0 on 2024-05-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaysite', '0005_alter_product_brand_alter_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
